### ISSUE TITLE
KeyError u'loco' Kodi Leia and Matrix

### ISSUE THREAD

**Issue by betatester3016** [CastagnaIT/plugin.video.netflix#1121]
#### Your Environment
- Netflix add-on version: 1.12.3
- Operating system version/name: CoreELEC (official): 9.2.7, kernel: Linux ARM 64-bit version 4.9.113 aarch64
- Device model:  Tanix TX5 Plus Deluxe Edition

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows
* [X] CoreELEC

### Describe the bug

When executing the Add-on after the Netflix Background Services have started, a Netflix Add-on Error window comes up displaying:

The Add-on encountered the following error:
Exception: KeyError
Error details:
u'loco'

#### Expected behavior

Netflix addon opening and showing categories list

#### Actual behavior

Error window comes up:
Exception: KeyError
Error details:
u'loco'

#### Steps to reproduce the behavior

1. Install CoreELEC
2. Install Netflix Addon 1.12.3
3. Login to Netflix account (I used a keyfile)
4. Open addon

#### Possible fix

Maybe an update broke something? 

### Debug log

The debug log can be found here:

https://paste.kodi.tv/uzojijiday.kodi
#### Other information

Add-on was working fine not even 24 hours ago.

**Comment by CastagnaIT** [comment]
Hi yesterday the netflix has made some changes in the website
and this has broken part of the addon,
i will have to check how to proceed

**Comment by jfabernathy** [comment]
I seem to have this same issue but wanted to add more reports of if. Log [https://paste.kodi.tv/qeranenohe](url)

**Comment by Ronny-nerd** [comment]
Have the same Problem.

PC - Windows 10 Pro = Kodi Leia 18.9 and Kodi Matrix19 Final
Nvidia Shield TV Pro 2019 = Kodi Leia 18.9 and Kodinerds Matrix19 Final

**Comment by tarlabasi** [comment]
Hi,
I have the same error.
LibreELEC Kodi Leia 18.9

**Comment by Ronny-nerd** [comment]
Thank you very much for the new fix ... CastagnaIT, now you can log into the Netflix add-on under Kodi 19 Matrix or Kodinerds 19 Matrix under Windows and Android and you can play everything again.

**Comment by Renoise2** [comment]
Netflix stopped working for me too, thank you for looking at it. Please add it to Kodi 18 too, we humble peons with RPI2/3 cannot install Kodi 19 yet.

**Comment by Sil3ntKn1ght** [comment]
> 
> 
> This is the fixed test version for Kodi 19 (Matrix): [plugin.video.netflix_1.14.1+matrix.1_20210331_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6236586/plugin.video.netflix_1.14.1%2Bmatrix.1_20210331_t1.zip)
> 
> if you update from this test file, remember to re-update manually from the addon repository when will be released the official version or Kodi will no longer update the addon
> 
> For Kodi 18 i will try soon

I'm on Windows 10,
Extracted and over wrote app data \AppData\Roaming\Kodi\addons with your file and Netflix Kodi is accessing menus etc.
will further test tomorrow, but is looking good.

you are very talented your work is appreciated greatly and the seed in this test file is amazing.

will report more tomorrow.

thank you

**Comment by jfabernathy** [comment]
fix worked on Android Shield TV, Thanks.

**Comment by t-morales** [comment]
Great! Fix worked for me in ubuntu 20.10 with kodi 19

**Comment by matthuo333** [comment]
Thanks for your reflect quickly. Look forward to update for Kodi 18 too.

**Comment by Ronny-nerd** [comment]
Thank you very much for the new Kodi Leia Fix ... CastagnaIT.

**Comment by matthuo333** [comment]
For Kodi 18, it is fixed.

**Comment by CastagnaIT** [comment]
thanks tomorrow i will do the releases

**Comment by okuyanf61** [comment]
> 
> 
> thanks tomorrow i will do the releases

thx

**Comment by Renoise2** [comment]
Awesome, thank you, it works! You are our Netflix hero :)

**Comment by ojessie** [comment]
Had the same problem running Kodi Leia 18.9 on PI 4. Fixed version fixed the problem. 

Thanks

**Comment by betatester3016** [comment]
Thank you for the fast response. The test versions work on CE 9.2.7 (Leia) and CE 19 (Matrix).

[Leia](https://github.com/CastagnaIT/plugin.video.netflix/files/6237757/plugin.video.netflix_1.12.3_20210331_t1.zip) test version (Kodi 18)

[Matrix](https://github.com/CastagnaIT/plugin.video.netflix/files/6236586/plugin.video.netflix_1.14.1%2Bmatrix.1_20210331_t1.zip) test version (Kodi 19)

Keep up the good work S.

**Comment by Sil3ntKn1ght** [comment]
> 
> 
> This is the fixed test version for Kodi 19 (Matrix): [plugin.video.netflix_1.14.1+matrix.1_20210331_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6236586/plugin.video.netflix_1.14.1%2Bmatrix.1_20210331_t1.zip)
> 
> if you update from this test file, remember to re-update manually from the addon repository when will be released the official version or Kodi will no longer update the addon
> 
> For Kodi 18 i will try soon

When clicking add to my list the following error come up

the add-on encountered the following error
typeError: Object of type Videoid is not JSON serializable

**Comment by BlissMediaSolutions** [comment]
Thanks for the quick fix.
Can confirm it worked on Win10 x64 Kodi 18 Leia

**Comment by CastagnaIT** [comment]
Keep issue opened until the official release will be out

i found a problem in the current fix that cause problems with playback by UpNext and Playlist
i need to check how to do

**Comment by CastagnaIT** [comment]
> Windows 10 Kodi Martix v19 Error on testing
> 
> description:
> When clicking add to my list the following error comes up
> 
> the add-on encountered the following error
> typeError: Object of type Videoid is not JSON serializable

thanks will check not related to this but due to last changes
this problem did not give me time to check if everything works

**Comment by Kidlike** [comment]
what would we do without you @CastagnaIT :love_you_gesture:

**Comment by Sil3ntKn1ght** [comment]
> 
> 
> > Windows 10 Kodi Martix v19 Error on testing
> > description:
> > When clicking add to my list the following error comes up
> > the add-on encountered the following error
> > typeError: Object of type Videoid is not JSON serializable
> 
> thanks will check not related to this but due to last changes
> this problem did not give me time to check if everything works

No problems, I'm happy to be a Ginny pig in testing. saves you time testing every sub menu etc.
many hand make light work.

**Comment by sergiorebol714** [comment]
Hello! thanks for the job! I was getting mad! yesterday i changed the group of a shared account and thought it was wrong! 
Same error with coreelec leia trying logging with Authentication Key. Fixed with the test addon https://github.com/CastagnaIT/plugin.video.netflix/files/6237757/plugin.video.netflix_1.12.3_20210331_t1.zip

**Comment by pypk1** [comment]
Thank you @CastagnaIT for this amazing plugin.  I still have an issue.  Unfortunately, as I was trying to debug the issue, I uninstall the plugin and reinstall it again.  Even with the new test version, I still cannot log in.  

The good news is that for other installations that I have, simply applying the updated version gets it back to work again.  Thanks again.

**Comment by p3t3n3t** [comment]
Great THX

**Comment by bagheerah** [comment]
I'm using windows 10, Kodi 18.5 and still keep getting the u'loco' error.
I've tried both copying the files and uninstalling and reinstalling Netflix 1.12.3 and none stops the error.
This is the kodi log: https://paste.kodi.tv/habifugula.kodi
Is the fix working for everybody else?
Any idea why?
Thanks in advance.

**Comment by Sil3ntKn1ght** [comment]
> 
> 
> I'm using windows 10, Kodi 18.5 and still keep getting the u'loco' error.
> I've tried both copying the files and uninstalling and reinstalling Netflix 1.12.3 and none stops the error.
> This is the kodi log: https://paste.kodi.tv/habifugula.kodi
> Is the fix working for everybody else?
> Any idea why?
> Thanks in advance.

I believe login is still a issue, if you backed up before removing your pass details are in
AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix

only over write 
AppData\Roaming\Kodi\addons

that what I did to get it working, Ironically my password changed today but in Kodi its still running with my old one lol
he said there are still issues its not final we are testing so your log should help if debug was on when you did it. I'm still new.
hopefully you had a backup and this helps till the final version

**Comment by kenpoduste** [comment]
Hi everyone,

I have raspberry with kodi 18.9. 

Today i started to detect the error. I tried to use the fix and it worked.

Thanks for your help!

**Comment by bagheerah** [comment]
No I've got it to work. Thanks a lot.

**Comment by plavenu** [comment]
On Librelec kodi 18.xx it work good.

Great thanks.

**Comment by ClausMM** [comment]
I run KODI 19.0 (Matrix) under Windows 10. 
With your _**plugin.video.netflix_1.14.1 + matrix.1_20210331_t1**_, the Netflix login works great again. 

Great thanks  and Happy Easter

**Comment by Ninoh-FOX** [comment]
Work again in raspbian, thanks!!

**Comment by DDE31** [comment]
Run OK with Leia/RPI4 !
Great job ! 
Thanks

**Comment by marcoriccine** [comment]
worked for me too! 
LibreELEC (official): 9.2.6 (RPi4.arm)
kodi leia
Thank's

**Comment by homerisback** [comment]
Worked fine on Odroid C2 with LibreElec Leia.
Thanks soooo much for this rocket fast patch !

**Comment by CeEs-atd** [comment]
plugin.video.netflix_1.12.3_20210331_t1.zip
LibreElec (official): 9.2.6 (RPi3b+)
Kodi Leia 18.9
Works fine with email+pwd! 
THANK YOU!

**Comment by dm2912** [comment]
dont know if related but i was getting this constantly during playback. but updating to git.master has fixed it
![screenshot00001](https://user-images.githubusercontent.com/25871666/113355235-59dc6600-9338-11eb-88bd-5b8efe42d076.png)

**Comment by Ronny-nerd** [comment]
> Keep issue opened until the official release will be out
> 
> i found a problem in the current fix that cause problems with playback by UpNext and Playlist
> i need to check how to do

Thank you very much for the new two Release for Kodi 19 Matrix and Kodi 18.9 Leia ...CastagnaIT.

**Comment by CastagnaIT** [comment]
I would like to thank those who sent me a little support,
the new fixed releases are out for Kodi 18 and 19

**Comment by morce** [comment]
Great job, working on K18

**Comment by jfabernathy** [comment]
What is the correct way to switch back from the test version to the release version?? I'm using K19 on Nvidia Shield TV and K18 on LibreELEC on RPI4.

**Comment by jozef-nemcok** [comment]
kodi leia, OSMC
loco issue fixed with 1.12.4 realease, but after successfull login to netflix, i cannot choose account. Activated is just first one with no way to change.

> 2021-04-02 14:12:11.664 T:1690271968   ERROR: [plugin.video.netflix (0)] IPC callback raised exception: It is not possible select a profile while a video is playing.
> 2021-04-02 14:12:11.700 T:1690271968   ERROR: [plugin.video.netflix (0)] Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 212, in _perform_ipc_return_call
>                                                 result = _call(func, data)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 252, in _call
>                                                 return func(data)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
>                                                 return func(*args, **kwargs)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/nfsession_ops.py", line 105, in activate_profile
>                                                 raise Warning('It is not possible select a profile while a video is playing.')
>                                             Warning: It is not possible select a profile while a video is playing.
> 2021-04-02 14:12:11.744 T:865063136   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 32, in wrapper
>                                                 func(*args, **kwargs)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 255, in run
>                                                 success = route(pathitems)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in lazy_login_wrapper
>                                                 return func(*args, **kwargs)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 129, in route
>                                                 _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 157, in _execute
>                                                 executor(pathitems=pathitems)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
>                                                 return func(*args, **kwargs)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 34, in set_custom_viewmode
>                                                 override_partial_setting_id = func(*args, **kwargs)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 100, in home
>                                                 if ret and not activate_profile(self.params['switch_profile_guid']):
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 148, in activate_profile
>                                                 common.make_call('activate_profile', guid)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 164, in timing_wrapper
>                                                 return func(*args, **kwargs)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 88, in make_call
>                                                 return make_addonsignals_call(callname, data)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 161, in make_addonsignals_call
>                                                 _raise_for_error(result)
>                                               File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 173, in _raise_for_error
>                                                 raise Exception(result['class'] + '\r\nError details:\r\n' + result.get('message', '--'))
>                                             Exception: Warning
>                                             Error details:
>                                             It is not possible select a profile while a video is playing.
> 2021-04-02 14:12:13.847 T:873455840   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/directory/home/?switch_profile_guid=7ZNMHR6SYRGJPOP2JEBGLXWXMA
> 2021-04-02 14:12:13.864 T:1916530704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/directory/home/?switch_profile_guid=7ZNMHR6SYRGJPOP2JEBGLXWXMA) failed

**Comment by CastagnaIT** [comment]
> 
> 
> What is the correct way to switch back from the test version to the release version?? I'm using K19 on Nvidia Shield TV and K18 on LibreELEC on RPI4.

**This is needed only for Kodi 19:**
Select Netflix icon, open context menu `Information`, you will see this:

![immagine](https://user-images.githubusercontent.com/3257156/113420436-9c9a4e80-93c9-11eb-915c-4ba65d6f3fb8.png)
"Origin" is set to `Manual` then to change it to `Repository`
you have to click on `Versions` button, and update to the last version from CastagnaIT repository

**Comment by Christophw2012** [comment]
Great job, working on K18 with corelec and odroid C2! Thank you very much, CastagnaIT!

**Comment by JonasAndrich** [comment]
> Here test version for Kodi 18 Leia: [plugin.video.netflix_1.12.3_20210331_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/6237757/plugin.video.netflix_1.12.3_20210331_t1.zip)

Thank you very much! Worked for us on Raspberry 3 with Kodi 18.2 with LibreELEC 9.0.2.

**Comment by Converted007** [comment]
> I would like to thank those who sent me a little support,
> the new fixed releases are out for Kodi 18 and 19

Sorry, but the new update didn't fix the issue. I still cannot login and keeps getting this error...
I used the key and the correct password. On a Pi3 with 18.9

**Comment by CastagnaIT** [comment]
**The test versions on the ZIP's of this thread are all bugged,
so please install the official version already released on the repository**

This thread is locked and kept as a reference for other users for a few more days
