### ISSUE TITLE
I'm unable to login with my valid credentials getting "loginContext" error.

### ISSUE THREAD

**Issue by ghost** [CastagnaIT/plugin.video.netflix#1674]
### Netflix add-on version

1.23.2

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I'm unable to login with my valid credentials getting "loginContext" error.

### Debug log - mandatory

https://paste.kodi.tv/azejucatit

**Comment by ccoenen** [comment]
I believe I'm seeing the same problem. Password used to work for years. Password hasn't changed. Re-entering password did not solve the problem for me.

**Comment by huaak** [comment]
I guess I face the same problem. Did a fresh install of libreelec on TV box, generated NFAuth-key, but neither with E-Mail & Password (here comes the "loginContext" error) or with the NFkey (here I get "Email field not found" Error) I can log in.

**Comment by MauriceW67** [comment]
I have the same issue as @huaak on my Nvidia Shield.

Logging in with the NFAuthentication.key prompts me for the PIN and then my password. Then the error "WebSiteParsingError: E-mail field not found" is displayed.

Logging in with ony e-mail and password gives me the loginContext error.

Note: I started the login process because the addon would not play content anymore (yesterday it was still working).

**Comment by MauriceW67** [comment]
@CastagnaIT I believe this is no longer working because Netflix changed the layout of the Account page. The e-mail address of the account is no longer visible on the main Overview page. You now need to go to the Security sub-section to see the e-mail address.

If I look at what's going on in access.py I think the WebSiteParsingError is being raised because the addon cannot find the e-mail address anymore.

**Comment by CastagnaIT** [comment]
to me still works correctly so i think netflix website is not updated for all countries or they have reverted changes on these last days idk...

the only errors found are what shown in the log above that i have just fixed
i will wait some days to see if also in my country change email position on the webpage

**Comment by huaak** [comment]
..here in Germany the new Layout on homepage is still active (for me)
![Bildschirmfoto_2024-02-04_15-31-27](https://github.com/CastagnaIT/plugin.video.netflix/assets/50967309/92202195-17c3-49bf-bb4b-9eb3cae27532)
..on those devices I already setup the netflix addon it still works like a charm, but I could not get any new device like laptop (linux) or tv box (libreelec) to log in via kodi..

**Comment by MauriceW67** [comment]
> ..on those devices I already setup the netflix addon it still works like a charm, but I could not get any new device like laptop (linux) or tv box (libreelec) to log in via kodi..

Same for me on the Dutch Netflix Account page.

As a workaround I temporarily changed line 127 in the access.py file from this:

`email = email_match.group(1).strip() if email_match else None`

to this:

`email = 'your e-mail address here'`

**Comment by yurtcuogluer** [comment]
Is that worked ?

**Comment by huaak** [comment]
> As a workaround I temporarily changed line 127 in the access.py file from this:
> 
> `email = email_match.group(1).strip() if email_match else None`
> 
> to this:
> 
> `email = 'your e-mail address here'`

Thank you very much-that saved my day..could now watch netflix on tv box in other room too..nice! :+1:

**Comment by yurtcuogluer** [comment]
I haven't located the access.py under ~/.Kodi/addons/plugin.video.netflix
No access.py.

**Comment by yurtcuogluer** [comment]
Okay checked the logs one more time. I've found the location of the file.
Thanks 👍

**Comment by anyc** [comment]
It works for me too with the change in access.py. Thank you

**Comment by yurtcuogluer** [comment]
Uh, I'm probably doing something wrong.

**Comment by huaak** [comment]
> Uh, I'm probably doing something wrong.

..if you found the access.py file in /.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/  just delete the 
`email = email_match.group(1).strip() if email_match else None part,`

and enter your Netflix-Account-Email with straight, single quotation mark ' (no ` ´ or ") before and after the address and it should work..

**Comment by MauriceW67** [comment]
@yurtcuogluer Note: My workaround only works for the login method with the .key file, not with e-mail/password.

**Comment by yurtcuogluer** [comment]
Thanks, I'll check it out!

**Comment by yurtcuogluer** [comment]
Oh how can I do it on Fedora should I need to install another tool?

**Comment by huaak** [comment]
..the only things you need(besides kodi, netflix addon, and chrome or chromium browser) are written in the description: [https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key](url)

**Comment by MauriceW67** [comment]
@huaak Not sure what happened, but the link you posted is somehow corrupt. Retry here:

https://github.com/CastagnaIT/plugin.video.netflix/wiki/Login-with-Authentication-key

**Comment by moderaterocker** [comment]
same issue here on my Ubuntu media server with Kodi 20.2.

This is the verbose log:

https://paste.kodi.tv/pibidenaqi

trying to apply the Maurice's workaround...

**Comment by moderaterocker** [comment]
Confirmed: the workaround... works! Thanks @MauriceW67

**Comment by yabba222** [comment]
> > ..on those devices I already setup the netflix addon it still works like a charm, but I could not get any new device like laptop (linux) or tv box (libreelec) to log in via kodi..
> 
> Same for me on the Dutch Netflix Account page.
> 
> As a workaround I temporarily changed line 127 in the access.py file from this:
> 
> `email = email_match.group(1).strip() if email_match else None`
> 
> to this:
> 
> `email = 'your e-mail address here'`

How doing this in Nvidia Shield TV Pro ?
I can't login in my Netflix account and under official app is only 540p output.

**Comment by ccoenen** [comment]
Will there be a fix for those of us who don't want to tinker with the plugin manually?

**Comment by MauriceW67** [comment]
> How doing this in Nvidia Shield TV Pro ?

Enable file sharing on your Nvidia Shield and then from a Windows PC in File Explorer browse to:

\\<IP address of Shield>\internal\Android\data\org.xbmc.kodi\files\.kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session

> I can't login in my Netflix account and under official app is only 540p output.

Did you ever copy your ESN from the official app to the Kodi addon? I made the mistake of doing that and since that time my official ESN has been blocked / resricted to 540p 😦

**Comment by yabba222** [comment]
> > How doing this in Nvidia Shield TV Pro ?
> 
> Enable file sharing on your Nvidia Shield and then from a Windows PC in File Explorer browse to:
> 
> \\internal\Android\data\org.xbmc.kodi\files.kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session
> 
> > I can't login in my Netflix account and under official app is only 540p output.
> 
> Did you ever copy your ESN from the official app to the Kodi addon? I made the mistake of doing that and since that time my official ESN has been blocked / resricted to 540p 😦

Thank's for help - but this metod not work for me.
I must lover my plan to HD  because 4K on my shield don't work anymore.

**Comment by HyknuF** [comment]
Damn, tinkered with the workaround on a rpi 3 with libreelec, but couldn't get it to work. did every step very carefully. still got error  "WebSiteParsingError: E-mail field not found". do you guys do something after changing the access.py? like clear cache of netflix addon, reboot or something? i also tried completely reinstall of netflixaddon and reboot etc. etc.   so far, it want work.

**Comment by MauriceW67** [comment]
@HyknuF Are you sure the access.py file that you changed is in this location:

.kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session

Also, you could try clearing the __pycache__ sub-directory to force a recompile of the .py files.

**Comment by HyknuF** [comment]
@MauriceW67 yes, path confirmed.  i changed it via ssh. 
honestly, no idea how to clear the cache. have to look for it. thanks for reply!

**Comment by MauriceW67** [comment]
@HyknuF Hmm I see that GitHub changed the spelling of pycache that I typed.

Each directory that contains .py files also contains a directory called [code]__pycache__[/code]

You can enter that with ssh and delete all the files in it.

**Comment by HyknuF** [comment]
@MauriceW67 thanks for clarifying, will try that. yes i tried with keyfile.

**Comment by HyknuF** [comment]
@MauriceW67 Ok, tested again but unfortunately same error. damn :-/

**Comment by MauriceW67** [comment]
@HyknuF Can you show how you edited the file? It should look like this (e-mail anonymized):

```
# Get the account e-mail
page_response = self.get('your_account').decode('utf-8')
email_match = re.search(r'account-email[^<]+>([^<]+@[^</]+)</', page_response)
email = 'xxxxx.yyyyy@gmail.com'
if not email:
raise WebsiteParsingError('E-mail field not found')

```

**Comment by rockabillycat666** [comment]
> > @HyknuF Can you show how you edited the file? It should look like this (e-mail anonymized):
> > ```
> > # Get the account e-mail
> > page_response = self.get('your_account').decode('utf-8')
> > email_match = re.search(r'account-email[^<]+>([^<]+@[^</]+)</', page_response)
> > email = 'xxxxx.yyyyy@gmail.com'
> > if not email:
> > raise WebsiteParsingError('E-mail field not found')
> > ```
> 
> @MauriceW67 The part in my access.py looks identical:
> 
> page_response = self.get('your_account').decode('utf-8') email_match = re.search(r'account-email[^<]+>([^<]+@[^</]+)</', page_response) email = '[my@email.com](mailto:my@email.com)' if not email: raise WebsiteParsingError('E-mail field not found')
> 
> i really don't get it why it don't work for me because as i read the workaround the first time it seemed to be clear that this should work straight.

Tried this and yeah... not working for me.. it gives also the loginContext error...

**Comment by Vincento00** [comment]
Does anyone know how to find and edit the access.py file in firestick 4k?

**Comment by yurtcuogluer** [comment]
if there's ssh server up and running u can make a ssh connection to your
device.

**Comment by Vincento00** [comment]
Could you please tell me how to start the ssh server.  Maybe there is another way to get to the firestick files?  Please help.

**Comment by WildPenquin** [comment]
The workaround described here does not work for me. I get the contextError and I am using the key log in method. Curiously, the account page has not been changed in my location (Finland), but still has the email on the front, there is no "security" subsection. I have also deleted all __pycache__.


I presume the errors I get are somewhat different and seem to point out at some localization part has broken:

```
2024-02-14 00:05:26.748 T:16661    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY                                                                                                    
2024-02-14 00:05:26.858 T:16767    info <general>: [plugin.video.netflix (1)] The debug logging is set as DISABLED                                                                                                 
2024-02-14 00:05:27.195 T:16769   error <general>: [plugin.video.netflix (0)] IPC callback raised exception:                                                                                                       
2024-02-14 00:05:27.199 T:16769   error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):                                                                                                   
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/cache_management.py", line 167, in get                                              
                                                       cache_entry = self._get_cache_bucket(bucket['name'])[identifier]                                                                                            
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^                                                                                            
                                                   KeyError: 'IEUWXOYKNJEIJO5IBHGTOBKHKA_loco_list'                                                                                                                
                                                                                                                                                                                                                   
                                                   The above exception was the direct cause of the following exception:                                                                                            
                                                                                                                                                                                                                   
                                                   Traceback (most recent call last):                                                                                                                              
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/cache_utils.py", line 70, in wrapper                                                  
                                                       return G.CACHE.get(_bucket, identifier)                                                                                                                     
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                     
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/cache_management.py", line 175, in get                                              
                                                       raise CacheMiss from exc                                                                                                                                    
                                                   resources.lib.common.exceptions.CacheMiss                                                                                                                       
                                                                                                                                                                                                                   
                                                   During handling of the above exception, another exception occurred:                                                                                             
                                                                                                                                                                                                                   
                                                   Traceback (most recent call last):                                                                                                                              
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 105, in handle_request                                        
                                                       ret_data = _call_func(func, pickle.loads(data))                                                                                                             
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 161, in _call_func                                            
                                                       return func(**data)                                                                                                                                         
                                                              ^^^^^^^^^^^^                                                                                                                                         
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper                                               
                                                       return func(*args, **kwargs)                                                                                                                                
                                                              ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_builder.py", line 80, in get_video_list              
                                                       list_id = self.get_loco_list_id_by_context(menu_data['loco_contexts'][0])                                                                                   
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                   
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_path_requests.py", line 90, in get_loco_list_id_by_co
ntext                                                                                                                                                                                                              
                                                       return next(iter(self.req_loco_list_root().lists_by_context([context], True)))[0]                                                                           
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                  
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/cache_utils.py", line 72, in wrapper                                                  
                                                       output = func(*args, **kwargs)                                                                                                                              
                                                                ^^^^^^^^^^^^^^^^^^^^^                                                                                                                              
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/directorybuilder/dir_path_requests.py", line 66, in req_loco_list_root    
                                                       path_response = self.nfsession.path_request(**call_args)                                                                                                    
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                    
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper                                               
                                                       return func(*args, **kwargs)                                                                                                                                
                                                              ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/path_requests.py", line 30, in path_request                       
                                                       response = self.post_safe(                                                                                                                                  
                                                                  ^^^^^^^^^^^^^^^                                                                                                                                  
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 75, in post_safe                                 
                                                       self.assert_logged_in()                                                                                                                                     
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 56, in assert_logged_in                          
                                                       raise NotLoggedInError                                                                                                                                      
                                                   resources.lib.common.exceptions.NotLoggedInError                                                                                                                
                                                                                                                                                                                                                   
2024-02-14 00:05:27.691 T:16772   error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):                                                                                                   
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 163, in login                                    
                                                       headers={'Accept-Language': _get_accept_language_string(react_context)},                                                                                    
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 263, in _get_accept_language_string              
                                                       supported_locales = react_context['models']['loginContext']['data']['geo']['supportedLocales']                                                              
                                                                           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^                                                                                                 
                                                   KeyError: 'loginContext'                                                                                                                                        
                                                                                                                                                                                                                   
2024-02-14 00:05:27.691 T:16772   error <general>: [plugin.video.netflix (0)] IPC callback raised exception: 'loginContext'                                                                                        
2024-02-14 00:05:27.693 T:16772   error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):                                                                                                   
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 105, in handle_request                                        
                                                       ret_data = _call_func(func, pickle.loads(data))                                                                                                             
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 164, in _call_func                                            
                                                       return func()                                                                                                                                               
                                                              ^^^^^^                                                                                                                                               
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper                                               
                                                       return func(*args, **kwargs)                                                                                                                                
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 163, in login
                                                       headers={'Accept-Language': _get_accept_language_string(react_context)},
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 263, in _get_accept_language_string
                                                       supported_locales = react_context['models']['loginContext']['data']['geo']['supportedLocales']
                                                                           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
                                                   KeyError: 'loginContext'
                                                                                                         
2024-02-14 00:05:27.700 T:16767   error <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 90, in lazy_login_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 130, in route
                                                       _execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS, root_handler)
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 159, in _execute
                                                       executor(pathitems=pathitems)
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py", line 28, in set_custom_viewmode
                                                       override_content_type = func(*args, **kwargs)
                                                                               ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py", line 164, in video_list
                                                       dir_items, extra_data = common.make_call('get_video_list', call_args)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 117, in make_http_call
                                                       raise _data
                                                   resources.lib.common.exceptions.NotLoggedInError
                                                                                                         
                                                   During handling of the above exception, another exception occurred:
                                                                                                         
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 265, in run
                                                       success = route(pathitems)
                                                                 ^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 97, in lazy_login_wrapper
                                                       if login(ask_credentials=not check_credentials()): 
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 42, in login
                                                       if common.make_call('login', credentials):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 117, in make_http_call
                                                       raise _data
                                                   KeyError: 'loginContext'
```
This is with the fix in place, but the error seems similar when there was no fix in place (I didn't scrutinize thoroughly).

**Comment by WildPenquin** [comment]
I realized I may have had a different error (loginContext error is not enough to determine for sure what is going on).

Deducing from the log and commit messages I realized I need the change from commit feb1351. After applying it I needed to relogin. I do not need the email fix.

**Comment by HyknuF** [comment]
@WildPenquin @MauriceW67  

Just tried the change of the commit, and now it works for me as well. But i was forced to use authentication key. mail/password still didn't work. thanks for your help guys!

**Comment by WildPenquin** [comment]
I've never used email/pw login, and judging from the wiki it is discouraged (IIRC I may have tried it a few years ago and it didn't work even back then for me).

I suppose Netflix service is under some refactoring, and we need to wait until things settle down and a new release is made.

**Comment by omalaspinas** [comment]
Hello,

I'm having the same error and the email fix does not work. I really don't understand what is happening because even if I remove the `raise` statement after the check for the email the exact same error persists... In the logs 

I'm using the .key authentification, and also tried to clear the __pycache__ directories. 

The code below without the `if not mail` to show the very weird error i get as you can see in the logs below. The error points to the commented code... Any ideas?

```python
    email='aaa@bbb.com'
    # Verify the password (with parental control api)
        try:
```

The logs I have :

```console
2024-02-15 08:41:52.736 T:835      info <general>: CActiveAESink::OpenSink - initialize sink
2024-02-15 08:41:52.736 T:835      info <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
2024-02-15 08:41:52.738 T:835      info <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=vc4hdmi0,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2024-02-15 08:41:52.738 T:835      info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-02-15 08:41:52.738 T:835      info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2024-02-15 08:41:52.986 T:3078    error <general>: GetDirectory - Error getting plugin://plugin.video.netflix/
2024-02-15 08:41:53.003 T:827     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
2024-02-15 08:41:54.703 T:827      info <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2024-02-15 08:42:07.098 T:3129    error <general>: [plugin.video.netflix (0)] IPC callback raised exception: E-mail field not found
2024-02-15 08:42:07.100 T:3129    error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 105, in handle_request
                                                       ret_data = _call_func(func, pickle.loads(data))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 161, in _call_func
                                                       return func(**data)
                                                              ^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 129, in login_auth_data
                                                       # Verify the password (with parental control api)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   resources.lib.common.exceptions.WebsiteParsingError: E-mail field not found
                                                   
2024-02-15 08:42:07.101 T:2963    error <general>: [plugin.video.netflix (6)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 265, in run
                                                       success = route(pathitems)
                                                                 ^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 88, in lazy_login_wrapper
                                                       if G.REQUEST_PARAMS.get('ignore_login') or _check_valid_credentials():
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 73, in _check_valid_credentials
                                                       if not login():
                                                              ^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 49, in login
                                                       if password and common.make_call('login_auth_data', {'data': data, 'password': password}):
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 117, in make_http_call
                                                       raise _data
                                                   resources.lib.common.exceptions.WebsiteParsingError: E-mail field not found
                                                   
2024-02-15 08:42:09.486 T:3110    error <general>: GetDirectory - Error getting plugin://plugin.video.netflix/
2024-02-15 08:42:09.503 T:827     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
```

**Comment by Konrades** [comment]
> > As a workaround I temporarily changed line 127 in the access.py file from this:
> > `email = email_match.group(1).strip() if email_match else None`
> > to this:
> > `email = 'your e-mail address here'`
> 
Many thanks from me too. Netflix will be discontinued for my Sony Bravia TV at the end of February and so yesterday I have tried my Raspberry 3B (updated to Libreelec 11, Kodi 20) using the plugin and NFAuth key. 
Same error "email field not found" with German Netflix account - changing the access.py line 127 today was the solution. 
Thanks again!

**Comment by maverickkk12** [comment]
Hola ¿me podriais explicar para un novato como llegar aqui?
/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/
tengo una tvbox tmax 95
Gracias

**Comment by crocketear** [comment]
Bonjour,
Sur Libreelec depuis Raspberry, j'arrive bien à trouver le répertoire /.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/ et le fichier acces.py mais je ne sais pas comment le modifier. 
Je n'ai pas d'option pour cela : je peux le lire, le renommer, le supprimer mais pas le modifier.
Merci de votre aide.
PS : /.kodi n'apparait pas dans le répertoire storage depuis un PC connecté en réseau à kodi.

**Comment by JungleJim42** [comment]
Hi Croketear! You must have admin privileges to modify this file. Try this command:
sudo gedit /.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py
You might have to change the "gedit" part depending on your text editor.

I can also confirm that the "access.py" modification resolved the problem for me (using the access token). On Ubuntu 22.04.

**Comment by theoden11** [comment]
Bonsoir. La manip de modif du fichier access.py, même après purge des caches, ne fonctionne pas. L'erreur "login context" reste identique, tant sur Kodi sous Windows 11 que sous Librelec installé sur une machine de salon autre que Raspberry. Dsl.

**Comment by Lsantag** [comment]
> Does anyone know how to find and edit the access.py file in firestick 4k?

kodi 19.5 . firetvstick 4k like yours
close kodi.  You need some (good) file explorer. I installed  "x-plore" app from amazon store it has smb support* .  xplore  "show hidden "  (important). Found access.py in route

/storage/emulated/0/Android/data/org.xbmc.Kodi/files/.Kodi/addons/plugin.video.netflix/resources/access.py
(it´s a 12kb file)
x-plore let you open the file "as text" and even edit it. BUT, I wasn´t  able to edit (no keyboard no idea how to do it). 
So, I *copied original access.py to a seagate lan disk  (any other smb or usb will be ok) and edit it in mi mac. Copy the edited file to smb disk again and  overwrite original using x-plore . (by the way i used smb disk to store generated NFAuthenticationKey.py too ). it works. sorry for my english

**Comment by jgavirias13** [comment]
Steps worked for me:
1. Connect to your Kodi server using ssh
2. Go to ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py
3. Edit the file (you can use gedit, nano, vi or the editor you have on your server)
4. Change the line 127 to:
email = 'example@example.com'
5. Save the file and exit the editor
6. Remove the content of ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/__pycache__/
7. Restart your kodi instance
8. Try to login again on netflix add-on using NFAuthenticationKey

**Comment by ccoenen** [comment]
@CastagnaIT might I pesker you into taking another look at this? This is an issue many seem to have (as evidenced by the large number of people posting their solutions or problems with the suggested workarounds here).

Would it be possible to roll these changes into a new release? Apparently the only problem lies in finding the email address on that page. People are changing this line here:

https://github.com/CastagnaIT/plugin.video.netflix/blob/feb1351badb5ee12bc7ddd16ad37b32b1764cab9/resources/lib/services/nfsession/session/access.py#L127

I am not familar with this codebase, but it looks like you're accessing https://www.netflix.com/YourAccount - or the API-equivalent of it? In my case, the email address *should* be matched by that regular expression, and still, it doesn't seem to work. Of course this was done in a web browser, and not from the script, so it might be different.

![html debugger in firefox showing a section of the netflix account page](https://github.com/CastagnaIT/plugin.video.netflix/assets/124909/ef269a98-4aa4-45f8-9d60-5628cd298c4d)

**Comment by theoden11** [comment]
> Steps worked for me:
> 
> 1. Connect to your Kodi server using ssh
> 2. Go to ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py
> 3. Edit the file (you can use gedit, nano, vi or the editor you have on your server)
> 4. Change the line 127 to:
>    email = '[example@example.com](mailto:example@example.com)'
> 5. Save the file and exit the editor
> 6. Remove the content of ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/**pycache**/
> 7. Restart your kodi instance
> 8. Try to login again on netflix add-on using NFAuthenticationKey

It works, endly, after several attemps. Thanks a lot.

**Comment by laermansjohan** [comment]
> Steps worked for me:
> 
> 1. Connect to your Kodi server using ssh
> 2. Go to ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py
> 3. Edit the file (you can use gedit, nano, vi or the editor you have on your server)
> 4. Change the line 127 to:
>    email = '[example@example.com](mailto:example@example.com)'
> 5. Save the file and exit the editor
> 6. Remove the content of ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/**pycache**/
> 7. Restart your kodi instance
> 8. Try to login again on netflix add-on using NFAuthenticationKey

This did the job for me, a big thanks.

**Comment by omalaspinas** [comment]
> Steps worked for me:
> 
>     1. Connect to your Kodi server using ssh
> 
>     2. Go to ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py
> 
>     3. Edit the file (you can use gedit, nano, vi or the editor you have on your server)
> 
>     4. Change the line 127 to:
>        email = '[example@example.com](mailto:example@example.com)'
> 
>     5. Save the file and exit the editor
> 
>     6. Remove the content of ~/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/**pycache**/
> 
>     7. Restart your kodi instance
> 
>     8. Try to login again on netflix add-on using NFAuthenticationKey

I was missing the reboot! Thanks!

**Comment by Rumatoyo** [comment]
I did it, I finally did it, it worked, the technique that you described here works, thank you brothers.

**Comment by Arshalali** [comment]
Does anyone know how to find and edit the access.py file in tv stick?
How to access Android data folder access denied

**Comment by haduvelko** [comment]
Is there any other workaround because my android tv is not rooted and i cannot acess android/data folder?

**Comment by Arshalali** [comment]
Download plugin zip file and unzip it. Use pydroid app from play store. Open access.py file in nf session folder in app. Change line 127. Save and zip the file using winzip app. Share zip file to tv. Open in kodi install from zip.

**Comment by haduvelko** [comment]
Thanks man, can i change that line in file with windows and than zip it and install it from zip in kodi.

**Comment by Arshalali** [comment]
Windows not required, pydroid app will work in Android mobile

**Comment by haduvelko** [comment]
I don't have android mobile just android tv and ios phone .

**Comment by Arshalali** [comment]
Check is pydroid app available for iOS app store. If no then nothing can be done, as iOS does not allow to modify like Android

**Comment by haduvelko** [comment]
Okay thanks again, i will try later to edit it with windows if i can, if not i will sidelod pydroid app to my android tv and edit line in file.

**Comment by Arshalali** [comment]
Pyto - Phyton 3 available in apple store as checked in Google. Check, i am not a iOS user

**Comment by haduvelko** [comment]
I will check but i think ios wont let me save it in zip file but i will try.

**Comment by Arshalali** [comment]
Yes, after you finish all process of login. There are further more steps to access netflix video playback in 540p quality only. Playback will stop after 2 minutes in higher quality. Message me after login

**Comment by haduvelko** [comment]
A editet line now i get error: name Error: name and after that my mail without @icloud.com just text before that.

**Comment by Arshalali** [comment]
Please explain in detail, i used gmail.com email id

**Comment by haduvelko** [comment]
![Uploading IMG_4667.jpeg…]()

**Comment by haduvelko** [comment]
![IMG_4667](https://github.com/CastagnaIT/plugin.video.netflix/assets/73912857/23a46629-00f9-4291-9755-d53c8d06d661)

**Comment by Arshalali** [comment]
Did you do it correctly 
Change line 127 to
email = 'your complete e-mail address here'

**Comment by haduvelko** [comment]
I do that

![IMG_4668](https://github.com/CastagnaIT/plugin.video.netflix/assets/73912857/2ebbbc64-01e2-4ffc-9c7c-48d5f1326e1b)

**Comment by haduvelko** [comment]
![IMG_4669](https://github.com/CastagnaIT/plugin.video.netflix/assets/73912857/2019e474-967e-4a63-9db5-88eec3076bc8)

**Comment by Arshalali** [comment]
Put your email in ' ' quotation marks

**Comment by haduvelko** [comment]
Thank you very much, finnally i'm loged in.

**Comment by Arshalali** [comment]
Check playback if playing after 2 minutes

**Comment by haduvelko** [comment]
Yes it is but there is no 4k just 1080p dolby vision and atmos.

**Comment by Arshalali** [comment]
Ok, well and good. Just for addition, update kodi to version 21.0 omega (stable) with apk sideload. And do following settings, if no playback after 2 minutes.

**Comment by Arshalali** [comment]
![Screenshot_2024-03-31-03-22-08-38_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/CastagnaIT/plugin.video.netflix/assets/151613889/07436e16-082c-45ef-8182-6d31e7d96be9)

**Comment by Arshalali** [comment]
Any other information required..?? Enjoy the addon

**Comment by haduvelko** [comment]
Thanks man, so there is no option for 4k resolution.

**Comment by Arshalali** [comment]
In Netflix addon settings, change to expert below and in playback set fixed video quality and resolution to uhd 4k, if your Android tv is 4k supported.

**Comment by haduvelko** [comment]
I tried now still 1080p nevermind thank you and sorry for bothering you.

**Comment by haduvelko** [comment]
Now it stops after 2 minutes weird.

**Comment by Arshalali** [comment]
As expected, follow my settings. You have to reduce quality to 540p. Reply if you want the steps

**Comment by ccoenen** [comment]
There are at least 24 people subscribed to this issue. I would like to request that we do *not* do individual techsupport on this issue.

Instead I really would like to re-iterate that this issue itself needs a fix. Not individual workarounds but a fix. If there is anything that is missing towards a real, next release fixing this for everyone affected, please let me know. I'm sure there are enough people in here that have analysed the problem in enough detail so this could lead to a more permanent, general fix of the problem.

**Comment by yabba222** [comment]
I think that the Netflix add-on from Castagna is over - what does it matter if I can log in if the playback time is only 2 minutes - as long as the trailer? Then the add-on stops working - do I mean stop playback? And if it does play, it only plays 540p (shield) or 1080p (other players).
If the author hasn't fixed it yet, it obviously can't be fixed. Let's thank him for many years of using this wonderful addition and let's say goodbye to him with dignity.

**Comment by Arshalali** [comment]
Please anyone inform the author one last time if he is able to fix

**Comment by Arshalali** [comment]
Has anyone informed, or explain me how to inform the author

**Comment by Arshalali** [comment]
@CastagnaIT Please check the add on, playback stops after 2 minutes and unable to login due to email field error.

**Comment by Rumatoyo** [comment]
Yes, I managed to enter but it stops after 2 minutes....well, I don't think there is a solution for now....thanks anyway

**Comment by Arshalali** [comment]
There is a solution of reducing quality to 540p only. But it is not a good solution

**Comment by CastagnaIT** [comment]
@ccoenen or someonelse
i have fixed login email problem, since recently netflix has allowed switching to new interface also on my country despite its not definitive but a test

if someone can give me a feedback that works, this is the test build:
[plugin.video.netflix_1.23.2+matrix.1_20240415_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/14979533/plugin.video.netflix_1.23.2%2Bmatrix.1_20240415_t1.zip)

**Comment by ccoenen** [comment]
with username/password, I'm still getting "unable to extract reactContext", I'm trying with authentication key next, but this will take a while.

**Comment by ccoenen** [comment]
Ok the `NFAuthentication.key` method worked! I am currently streaming something from netflix, let's see how it goes :-D  but this is progress for sure!

**Comment by CastagnaIT** [comment]
> with username/password, I'm still getting "unable to extract reactContext", I'm trying with authentication key next, but this will take a while.

the login page is changed, now part of HTML is protected by reCaptcha
therefore reactContext cant be read because become available later time
since reactContext is needed to get the authURL to perform the login request
in this way the website completely _cut off_ any attempt to perform the login through external softwares or scripts,
at least for now but i don't think they will come back from this website change...

the only way to remedy this is to implement reCaptcha v3 tokenized
and this is totally out of my competences, since implement reCaptcha decoding its not an easy thing to do and require also a webservice that elaborate these tokens

the only thing i could do now is try to simplify the login with auth
but still the addon is quite unusable because of the playback problems due to license request
i have updated #1627 issue with my last findings, but i alone can do nothing more

**Comment by ccoenen** [comment]
I've read through the NFauth python script, and if I read it correctly, the only thing you need are the cookies from a logged in session, right? If that's the case, maybe a bookmarklet would be a way for a somewhat larger audience?

**Comment by CastagnaIT** [comment]
yes there is need of session cookies
i think bookmarklets are a bit not so safe

at this point if we don't give a damn about any kind of protection maybe already exists a browser extension that allow extract all website page cookies in to a file

**Comment by ccoenen** [comment]
so the information you can extract is not exactly the same. The question is: does that matter?

The python method gets you these keys: `name`, `value`, `domain`, `path`, `expires`, `size`, `httpOnly`, `secure`, `session`, `priority`, `sameParty`, `sourceScheme`, `sourcePort`. Most of these keys don't really matter, because your browser does not send anything but `name` and `value`. All the other keys don't go over the network but determine where the cookies may be sent.

This JavaScript gets you only `name` and `value` because that's all the `document.cookies` gives you back. Do you think this could still work?

```javascript
(function () {
  const output = {app_name: "NFAuthenticationKey", data: {cookies: {}}};
  document.cookie.split(/;\s*/).forEach(c => {
    const [name, value] = c.split("=")
		output.data.cookies[name] = value;
  });
  console.log(output);
}());
```

This can be run from your browser's console and should output a json file structurally identical to what's currently created. (I left out a few fields that are easily added later)

![grafik](https://github.com/CastagnaIT/plugin.video.netflix/assets/124909/1ad87e72-dd7a-49d5-ada0-e7f3e9beaea5)

If you think this is worthwhile pursueing, I can look into the web crypto api, which can do AES-CBC and base64 is of course not a problem. My screenshot above is from Firefox, but this would probably work across browsers and would not require users to install python and dependencies.

**Comment by CastagnaIT** [comment]
@ccoenen I would like not to spam this Issue thread, it is better to create a new Issue where we can discuss these possibilities to make "auth key" easier

> Most of these keys don't really matter, because your browser does not send anything 

from what i remember from the implementation in the past, these values were there, if something has changed in the meantime and the browser no longer provides this data i don't know, I will have to check again
I see no reasons not to include cookies params if exists

**Comment by Arshalali** [comment]
Playback issue in Android tv and other devices too. Playback stops after 2 minutes. Fix the issue at the earliest to watch in 4k quality. As working now in 540p.

**Comment by CastagnaIT** [comment]
@Arshalali read the thread: #1627

**Comment by Arshalali** [comment]
@CastagnaIT I understand that now the netflix videos are encrypted format. From when did Netflix started this, whether it was not encrypted before..??

**Comment by CastagnaIT** [comment]
On the Issue i specified I have already specified the necessary,
if you have no expertise regarding DRM systems
there is no point in giving you further answers this doesn't help me and just wastes time

**Comment by Arshalali** [comment]
@CastagnaIT Is there any progress in fixing the issue since September 2023..?? Is there any possibility to get it resolved in future..??
