### ISSUE TITLE
WebsiteParsingError

### ISSUE THREAD

**Issue by untiiis** [CastagnaIT/plugin.video.netflix#1726]
### Netflix add-on version

1.23.3

### Operative systems used

Android, Windows

### Kodi version used

Other (specify in description)

### Description of the bug

Good morning 
I still have a connection error 

WebParsingError, on last kodi update

I read the other issues, I didn't find a solution

                      

### Debug log - mandatory

https://paste.kodi.tv/ataqewupas

**Comment by biocoder-frodo** [comment]
@untiiis  that debuglog is too short to see the actual error? On what line did the script crash?
Look for `The above exception was the direct cause of the following exception:`

**Comment by biocoder-frodo** [comment]
Ok, that looks exactly like the error I fixed with the plugin on my libreElec install. 
Could you try to change `C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\website.py` as displayed [here](https://github.com/CastagnaIT/plugin.video.netflix/commit/f31989d013d32e04de495703152d35523f076cd3).
Do this before starting Kodi and look in the `C:Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\__pycache__` folder to remove the Python byte code equivalent of the source code you just changed. Then I'm curious what will happen if you start Kodi and try again. Please note I used the login method with the NFAuthenticationKey file.

**Comment by untiiis** [comment]
@biocoder-frodo 

I replaced the line of code, deleted the cache
But I still get the same error.

https://paste.kodi.tv/wekonifega



2024-12-03 15:50:45.257 T:7516    error <general>: [plugin.video.netflix (0)] IPC callback raised exception: Unable to extract reactContext
2024-12-03 15:50:45.258 T:7516    error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\website.py", line 282, in extract_json
                                                       json_str = json_array[0]
                                                   IndexError: list index out of range
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\http_server.py", line 105, in handle_request
                                                       ret_data = _call_func(func, pickle.loads(data))
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\http_server.py", line 161, in _call_func
                                                       return func(**data)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\nfsession\session\access.py", line 112, in login_auth_data
                                                       website.extract_session_data(self.get('browse'), validate=True, update_profiles=True)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\website.py", line 72, in extract_session_data
                                                       react_context = extract_json(content, 'reactContext')
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\website.py", line 298, in extract_json
                                                       raise WebsiteParsingError(f'Unable to extract {name}') from exc
                                                   resources.lib.common.exceptions.WebsiteParsingError: Unable to extract reactContext
                                                   
2024-12-03 15:50:45.260 T:5804    error <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 265, in run
                                                       success = route(pathitems)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 88, in lazy_login_wrapper
                                                       if G.REQUEST_PARAMS.get('ignore_login') or _check_valid_credentials():
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\run_addon.py", line 73, in _check_valid_credentials
                                                       if not login():
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\api_requests.py", line 58, in login
                                                       if password and common.make_call('login_auth_data', {'data': data, 'password': password}):
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\utils\logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                     File "C:\Users\Legion\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py", line 117, in make_http_call
                                                       raise _data
                                                   resources.lib.common.exceptions.WebsiteParsingError: Unable to extract reactContext
                                                   
2024-12-03 15:50:45.270 T:13720    info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-12-03 15:50:47.834 T:13720 warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2024-12-03 15:50:47.901 T:11716    info <general>: Skipped 3 duplicate messages..
2024-12-03 15:50:47.901 T:11716   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.netflix/

**Comment by biocoder-frodo** [comment]
When did you create the NFAuthenticationKey file?

**Comment by mlc42** [comment]
with a new created NFAuthenticationKey it ends up with

2024-12-10 19:57:47.493 T:1320    error <general>: [plugin.video.netflix (0)] IPC callback raised exception: E-mail field not found
2024-12-10 19:57:47.500 T:1320    error <general>: [plugin.video.netflix (0)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 105, in handle_request
                                                       ret_data = _call_func(func, pickle.loads(data))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/http_server.py", line 161, in _call_func
                                                       return func(**data)
                                                              ^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/services/nfsession/session/access.py", line 129, in login_auth_data
                                                       raise WebsiteParsingError('E-mail field not found')
                                                   resources.lib.common.exceptions.WebsiteParsingError: E-mail field not found
                                                   
2024-12-10 19:57:47.508 T:1303    error <general>: [plugin.video.netflix (1)] Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 29, in wrapper
                                                       func(*args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 265, in run
                                                       success = route(pathitems)
                                                                 ^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 88, in lazy_login_wrapper
                                                       if G.REQUEST_PARAMS.get('ignore_login') or _check_valid_credentials():
                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 73, in _check_valid_credentials
                                                       if not login():
                                                              ^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/api_requests.py", line 49, in login
                                                       if password and common.make_call('login_auth_data', {'data': data, 'password': password}):
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py", line 139, in timing_wrapper
                                                       return func(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 94, in make_call
                                                       return make_http_call(endpoint, func_name, data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 117, in make_http_call
                                                       raise _data
                                                   resources.lib.common.exceptions.WebsiteParsingError: E-mail field not found

**Comment by mlc42** [comment]
I load the latest version from github and after reboot of raspi reinstall netflix addon.
Now i can login with new created NFAuthenticationKey and netflix works again.

**Comment by cow-crash** [comment]
Do place fixed commit for 'normal' updates next time? or should i download code here for myself. i like this app, but i don't know exactly how to download and install for myself :(

**Comment by TonySchmitt** [comment]
Same thing my dad use the extension but don't know what is git... Any chance to have a version with the correction ?
