### ISSUE TITLE
next page does not work

### ISSUE THREAD

**Issue by doradojc** [CastagnaIT/plugin.video.netflix#257]
#### Your Environment
- Netflix add-on version: plugin.video.netflix_0.15.5_20191017
- Operating system version/name: LibreELEC-RPi2.arm-9.1.501.img.gz
- Device model: Raspberry Pi 3

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [x] Libreelec
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
In the list of videos the next page button does not work, when there are more than 98 episodes in a series
#### Expected behavior
show the second page with videos of 99 and following

#### Actual behavior
reload page 1

#### Steps to reproduce the behavior
1. select serie
2. select season
3. If the season has more than 98 chapters, the following page button appears but they do not work

#### Possible fix
Error on pagination, change the limit of 100 items in the list

**Comment by CastagnaIT** [comment]
i think this already solved in current master
is close to release new version

**Comment by CastagnaIT** [comment]
new version released

**Comment by doradojc** [comment]
Sorry, but the issue still exists, the button "next page" does not work
![Firefox_Screenshot_2019-10-28T13-35-47 790Z](https://user-images.githubusercontent.com/45236847/67682855-a911b080-f966-11e9-8446-25328945d619.png)

**Comment by CastagnaIT** [comment]
what tvshow and what season?

**Comment by doradojc** [comment]
the link on netflix is https://www.netflix.com/title/70269145 
that series has 335 episodes
![serie](https://user-images.githubusercontent.com/45236847/67683433-cb57fe00-f967-11e9-93fc-9fa8f4e8a79a.jpg)

**Comment by CastagnaIT** [comment]
this tvshow is not available in my country, i can not do test...
another tvshow?

**Comment by doradojc** [comment]
sorry I couldn't find more series of more than 95 episodes in one season, maybe this works?
https://www.netflix.com/title/81091825

**Comment by CastagnaIT** [comment]
again nothing... open nothing

**Comment by leojsu** [comment]
The same thing happens to me with the same series. What can they do to fix it?

**Comment by scmanjarrez** [comment]
Can you test with "Pasión de gavilanes"? It has more than 95 episodes. @CastagnaIT 
Netflix Spain, btw.

**Comment by CastagnaIT** [comment]
this is available also in my country thanks!
now i can do some tests

**Comment by CastagnaIT** [comment]
Fixed you can install daily build or wait the next release

**Comment by scmanjarrez** [comment]
Thanks!
